# Generated by Django 5.2.5 on 2025-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
