# Generated by Django 5.2.5 on 2025-08-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='atendimentoveterinario',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statusatendimento'),
        ),
    ]
